[tool.poetry]
name = "mikrostack"
version = "0.1.0"
description = ""
authors = ["Emil Larsson <emil.larsson@nordlo.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
